version: '3.4'

services:
  front:
    build:
      # context: ./frontend
      dockerfile: Dockerfile
    restart: always
    # stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    # environment:
    #   CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./src:/app/src
